version: "3.8"

services:
  banco_de_dados:
    build:
      context: .
      dockerfile: Dockerfile.pgcron
    container_name: game_banco_de_dados
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5

  controlador_de_migrations:
    image: flyway/flyway:latest
    container_name: game_controlador_de_migrations
    depends_on:
      - banco_de_dados
    environment:
      FLYWAY_URL: jdbc:postgresql://banco_de_dados:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations:/flyway/sql
    entrypoint: ["flyway", "migrate"]

volumes:
  postgres_data:
